### ISSUE TITLE
This code is stolen from a private repo.

### ISSUE THREAD

**Issue by Cyuubi** [kem0o/neonitev2#1]
Hi everyone, I'm here to announce that this code is stolen from a private repo. Check `oauth.js` and compare it to the original (private) FDev server code, basically everything is stolen.

![image](https://user-images.githubusercontent.com/24927193/83209811-38fb2100-a127-11ea-835d-1923e98a9b4c.png)

**Comment by AstralFN** [comment]
asddat gegwgsdfkjbgsdjkbegwjbkwgebjhkgwerbjkhqfebjkgrwjbkfebjkeaf

**Comment by kem0o** [comment]
it's not stolen it's called "common sense" and you can stop being annoying and fuck off and at least show me what you can do , yeah Ig you can only be annoying not working :)

**Comment by Cyuubi** [comment]
You literally also stole my `AuroraNative.dll` even after I nicely requested you to remove it, whatever.

**Comment by Cyuubi** [comment]
Also, it's not common sense you imbecile. It's literally just you copy-pasting source code, because you're too lazy to write your own server.

**Comment by Cyuubi** [comment]
So, keep spreading lies. You love to censor people.

**Comment by Slushia** [comment]
![kemo](https://user-images.githubusercontent.com/56281030/83210586-41ecf200-a129-11ea-9cdd-de22f18ec1d5.png)
